# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  app_id: 131336175362
  secret: f7b15a925058e7be60f0a4d56294e938

production:
  app_id: 131336175362
  secret: f7b15a925058e7be60f0a4d56294e938

test:
  app_id: 131336175362
  secret: f7b15a925058e7be60f0a4d56294e938
